upsert_rule:
  name: Install or update rule
  fields:
    rule_json:
      required: true
      selector:
        text:
          multiline: true
remove_rule:
  name: Remove rule
  fields:
    rule_id:
      required: true
      selector:
        text:
create_helper:
  name: Create Elysium helper
  fields:
    helper_json:
      required: true
      selector:
        text:
          multiline: true
update_helper:
  name: Update Elysium helper
  fields:
    helper_json:
      required: true
      selector:
        text:
          multiline: true
delete_helper:
  name: Delete Elysium helper
  fields:
    helper_id:
      required: true
      selector:
        text:
set_helper:
  name: Set Elysium helper state
  fields:
    helper_id:
      required: true
      selector:
        text:
    state:
      required: true
      selector:
        text:
